#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# The Companion's store submission (companion-24): the first end-to-end
# build to full App Store review with MANUAL release, and to Play internal
# testing. Run from anywhere:
#
#   app/companion-shell/scripts/store-submit.sh
#
# It asks before every upload and every submit. The only file it writes is
# android/keystore.properties (gitignored), plus the publisher key's
# PUBLIC half into src/shell/bundle/publisherKey.ts when you give it one.
# App Store Connect and Play Console labels are as of September 2026: if
# one has moved, follow the page, not this script.

SHELL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$(cd "$SHELL_DIR/.." && pwd)"
STORE="$SHELL_DIR/store"
PIN_FILE="$SHELL_DIR/src/shell/bundle/publisherKey.ts"
ENV_FILE="$SHELL_DIR/android/keystore.properties"
BUNDLE_ID="com.gavin.companion"
WORK="${TMPDIR:-/tmp}/gavin-companion-store"
mkdir -p "$WORK"

# clip FILE copies one of store/'s texts to the clipboard, for pasting.
clip() {
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$STORE/$1"
    printf '  %s⧉ copied%s store/%s to the clipboard\n' "$GREEN" "$RESET" "$1"
  else
    note "copy it from app/companion-shell/store/$1"
  fi
}

TOTAL_STAGES=11

banner "Gavin Companion: App Store review + Play internal testing"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The publisher key (pin its public half)"
if grep -q 'PUBLISHER_KEY: string | null = null' "$PIN_FILE"; then
  say "The shell pins no publisher key yet, so a store build would refuse every"
  say "Workstation's bundle. Only the Demo Workstation would open."
  say "On a machine that runs NO agents (docs/RELEASING.md, \"The Companion bundle key\"):"
  step "cd app && node src-tauri/companion-key.mjs generate"
  step "Keep the seed there: gh secret set GAVIN_BUNDLE_SIGNING_KEY  (paste the seed)"
  step "Never paste the seed into this machine or this wizard."
  ask PUBLIC_KEY "Paste the PUBLIC key it printed (Enter to skip):"
  if [[ -n "$PUBLIC_KEY" ]]; then
    if [[ ! "$PUBLIC_KEY" =~ ^[0-9a-fA-F]{64}$ ]]; then
      warn "that is not 64 hex characters; nothing pinned"
      SKIPPED+=("pin the publisher key in src/shell/bundle/publisherKey.ts")
    else
      sed -i.bak "s/PUBLISHER_KEY: string | null = null;/PUBLISHER_KEY: string | null = \"$PUBLIC_KEY\";/" "$PIN_FILE"
      rm -f "$PIN_FILE.bak"
      printf '  %s✓ pinned%s in %s (commit it)\n' "$GREEN" "$RESET" "$PIN_FILE"
    fi
  else
    warn "skipped: this build will open only the Demo Workstation"
    SKIPPED+=("pin the publisher key in src/shell/bundle/publisherKey.ts")
  fi
else
  say "publisherKey.ts already pins a key."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer: the App ID"
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "If $BUNDLE_ID is not listed: + → App IDs → App → Continue."
step "Description \"Gavin Companion\", Bundle ID Explicit: $BUNDLE_ID."
step "No capabilities: Face ID, the keychain and the camera need none. Register."
ask APPLE_TEAM_ID "Your Team ID (Membership details, 10 characters):"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: the app record"
open_url "https://appstoreconnect.apple.com/apps"
step "If Gavin Companion is not there: + → New App."
step "Platform iOS · Name: Gavin Companion (store/listing.txt) · Primary language English (U.S.)"
step "Bundle ID $BUNDLE_ID · SKU gavin-companion · User access Full. Create."
note "The name must be unique across the App Store. If it is taken, pick another"
note "and change it in store/listing.txt too. The home-screen name stays \"Gavin\"."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Play Console: the app"
open_url "https://play.google.com/console"
step "If Gavin Companion is not there: Create app."
step "App name Gavin Companion · English (United States) · App · Free."
step "Accept the declarations. Create app."
note "Play App Signing is on by default: Play keeps the signing key, and you"
note "upload with an upload key (the next stage)."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Android: the upload key"
say "The upload key signs what you send to Play. Keep it OUTSIDE the repository."
UPLOAD_JKS_DEFAULT="$HOME/.gavin-keys/companion-upload.jks"
if [[ -f "$UPLOAD_JKS_DEFAULT" ]]; then
  say "Found $UPLOAD_JKS_DEFAULT."
else
  step "Make one (it asks for a password, twice):"
  say "  mkdir -p ~/.gavin-keys && keytool -genkeypair -v -keystore $UPLOAD_JKS_DEFAULT \\"
  say "    -alias upload -keyalg RSA -keysize 4096 -validity 10000"
  pause "Press Enter once it exists"
fi
ask storeFile "Keystore path [$UPLOAD_JKS_DEFAULT]:"
storeFile="${storeFile:-$UPLOAD_JKS_DEFAULT}"
ask keyAlias "Key alias [upload]:"
keyAlias="${keyAlias:-upload}"
ask_secret storePassword "Keystore password:"
ask_secret keyPassword "Key password (Enter if the same):"
keyPassword="${keyPassword:-$storePassword}"
write_env storeFile "$storeFile"
write_env keyAlias "$keyAlias"
write_env storePassword "$storePassword"
write_env keyPassword "$keyPassword"
note "keystore.properties is gitignored. Back the .jks and its password up somewhere"
note "safe: losing them means asking Play support for an upload key reset."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Build both stores' binaries"
say "Syncs a RELEASE build (no dev key, no probe) and builds the iOS archive and the Android AAB."
ask BUILD_NUMBER "Build number (1 for the first upload; one higher on each later upload):"
BUILD_NUMBER="${BUILD_NUMBER:-1}"
if confirm "Build now? (a few minutes)"; then
  (cd "$APP_DIR" && npm run companion-shell:sync -- ios android --release)
  xcodebuild -project "$SHELL_DIR/ios/App/App.xcodeproj" -scheme App -configuration Release \
    -destination 'generic/platform=iOS' -archivePath "$WORK/App.xcarchive" \
    -allowProvisioningUpdates DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER" archive
  (cd "$SHELL_DIR/android" && ./gradlew bundleRelease -PversionCodeOverride="$BUILD_NUMBER")
  printf '  %s✓ built%s %s and android/app/build/outputs/bundle/release/app-release.aab\n' "$GREEN" "$RESET" "$WORK/App.xcarchive"
else
  SKIPPED+=("build: npm run companion-shell:sync -- ios android --release, then archive and bundleRelease")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: upload the build"
cat > "$WORK/ExportOptions.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store-connect</string>
  <key>destination</key><string>upload</string>
  <key>teamID</key><string>$APPLE_TEAM_ID</string>
  <key>manageAppVersionAndBuildNumber</key><false/>
</dict>
</plist>
PLIST
if [[ -d "$WORK/App.xcarchive" ]] && confirm "Upload build $BUILD_NUMBER to App Store Connect? (a build number can be uploaded only once)"; then
  xcodebuild -exportArchive -archivePath "$WORK/App.xcarchive" \
    -exportOptionsPlist "$WORK/ExportOptions.plist" -exportPath "$WORK/export" -allowProvisioningUpdates
  say "Uploaded. App Store Connect takes a few minutes to process it."
else
  note "Or: open $WORK/App.xcarchive in Xcode → Organizer → Distribute App → App Store Connect."
  SKIPPED+=("upload the iOS archive to App Store Connect")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: the listing"
open_url "https://appstoreconnect.apple.com/apps"
step "Gavin Companion → the 1.0 version (iOS App, Prepare for Submission)."
step "Screenshots: iPhone 6.9\" (1320×2868). If the app stays iPhone + iPad, iPad 13\" (2064×2752) too."
note "  A Simulator of that size, the Demo Workstation open: xcrun simctl io <udid> screenshot shot.png"
note "  Show only what this build does: the hub, the workspace list and a board."
step "Paste the Description:"; clip description.txt
pause "Press Enter for the rest of the listing"
step "Subtitle, Keywords and Promotional Text: from store/listing.txt."; clip listing.txt
step "Support URL (required): the Gavin site or repository page."
step "App Information → Category: Developer Tools. Content Rights: no third-party content."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: privacy, age rating, encryption"
step "App Privacy → Privacy Policy URL (required for every app)."
step "App Privacy → Data Collection: \"No, we do not collect data from this app\"."
note "  The app sends data only to the user's own desktop, through a Relay that"
note "  forwards end-to-end encrypted bytes. It has no account, analytics or ads."
note "  (The binary's PrivacyInfo.xcprivacy says the same.) This is your answer to give."
step "Age Rating: answer the questionnaire (no objectionable content)."
step "Encryption (asked when you pick the build): it DOES use encryption beyond"
say  "  Apple's own: Noise (X25519, ChaCha20-Poly1305, BLAKE2s) and Ed25519, all"
say  "  standard algorithms, to protect the user's own data in transit. Which"
say  "  exemption applies (and France's declaration) is your legal answer."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "App Store Connect: review notes, MANUAL release, submit"
step "Build: + → pick build $BUILD_NUMBER once it has processed; answer the encryption questions."
step "App Review Information: Sign-in required OFF (the Demo Workstation needs none)."
step "Contact name, phone, email. Notes: paste:"; clip app-review-notes.txt
step "App Store Version Release: \"Manually release this version\". NOT automatic."
warn "Approval must not publish. Check Manual release before you submit."
if confirm "Manual release is selected and everything above is filled. Submitted it for review?"; then
  ask ASC_SUBMITTED "Version and build as App Store Connect shows it (e.g. 1.0 (1)):"
else
  SKIPPED+=("App Store: submit version 1.0 for review with Manual release")
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Play Console: internal testing"
open_url "https://play.google.com/console"
step "Gavin Companion → Test and release → Testing → Internal testing → Testers: add an email list with yourself."
step "Create new release → upload android/app/build/outputs/bundle/release/app-release.aab"
step "Release name: 1.0 ($BUILD_NUMBER). Release notes: paste:"; clip play-release-notes.txt
step "Main store listing (if Play asks): short description from store/listing.txt,"
say  "  full description from store/description.txt, icon store/play-icon-512.png."
note "  Play may hold the rollout until Dashboard tasks (privacy policy, data safety,"
note "  content rating, target audience) are done. Do the ones it names. A 1024×500"
note "  feature graphic is not prepared here."
if confirm "Rolled it out to Internal testing (not production)?"; then
  ask PLAY_RELEASE "Release name as Play shows it:"
else
  SKIPPED+=("Play: roll the AAB out to Internal testing")
fi

finish
say "Record on the companion-24 card (.gavin-root/plans/companion-24-early-store-review.md):"
[[ -n "${ASC_SUBMITTED:-}" ]] && say "  App Store: submitted $ASC_SUBMITTED for review, Manual release, $(date +%F)"
[[ -n "${PLAY_RELEASE:-}" ]] && say "  Play internal testing: $PLAY_RELEASE, $(date +%F)"
say "Then, when App Review replies, answer the card's Decision with its verdict."
